package BeforeLogin;

import Admin.*;
import MySQLConnections.*;
import java.sql.*;
import javax.swing.JOptionPane;

/** Author and License
 * 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * 
 * @author ray njire
 */
public class AdminLogin extends javax.swing.JFrame 
{
    //Common Variables
    String SQLCode;
    Connection conn;
    Statement NewStatement;
    ResultSet myResultSet;
    
    //These Arrays hold the UserName and Cart Number before passing it to the next page
    String loggedin[] = new String [1];
    
    //Function that holds the Array Input for Passing UserName
    public void PassingUserName()
    {
        try
        {
            //Passing the Username. Insert into Array slot 0 the name of the user
            loggedin[0] = TXTUserName.getText().toUpperCase();
        
        }
        
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage() + "\n\nError Initializing Array to Pass UserName", "", JOptionPane.ERROR_MESSAGE);
            
        }
    }
    
    //Creates new form AdminLogin
    public AdminLogin() 
    {
        //Personalized Default Frame Appearance
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        
        //Hide Components
        CHKBXPassword.hide();
    }
    
    //Method to execute Any SQL Statements that run in this Class
    public void executeSQLQuery (String query)
    {
        try
        {
            //Check MySQL Connection
            conn = MySQLConnect.ConnectDB();
            
            //Holds the SQL Statements that are run
            NewStatement = conn.createStatement();
            
            //Executes the Query
            NewStatement.executeUpdate(query);
            
        }
        
        //Error Handling the Update Statement
        catch (SQLException sqle)
        {
            JOptionPane.showMessageDialog(null, sqle.getMessage());
            
        }
    }
    
    /**Default Instantiation Function
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PNL1 = new javax.swing.JPanel();
        LBLLogo = new javax.swing.JLabel();
        LBLUserName2 = new javax.swing.JLabel();
        TXTUserName = new javax.swing.JTextField();
        LBLPassword2 = new javax.swing.JLabel();
        TXTPassword = new javax.swing.JPasswordField();
        CHKBXPassword = new javax.swing.JCheckBox();
        BTNOK = new javax.swing.JButton();
        BTNClearAll = new javax.swing.JButton();
        BTNBACK = new javax.swing.JButton();
        BTNExit = new javax.swing.JButton();
        LBLBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMINISTRATOR LOGIN PAGE");
        setResizable(false);

        PNL1.setLayout(null);

        LBLLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BigBargainPhotos/Big Bargains Store Logo.jpg"))); // NOI18N
        PNL1.add(LBLLogo);
        LBLLogo.setBounds(30, 20, 300, 300);

        LBLUserName2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        LBLUserName2.setForeground(new java.awt.Color(255, 255, 255));
        LBLUserName2.setText("UserName: ");
        PNL1.add(LBLUserName2);
        LBLUserName2.setBounds(370, 50, 74, 18);

        TXTUserName.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        TXTUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTUserNameActionPerformed(evt);
            }
        });
        PNL1.add(TXTUserName);
        TXTUserName.setBounds(460, 40, 200, 40);

        LBLPassword2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        LBLPassword2.setForeground(new java.awt.Color(255, 255, 255));
        LBLPassword2.setText("Password: ");
        PNL1.add(LBLPassword2);
        LBLPassword2.setBounds(370, 120, 69, 18);

        TXTPassword.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        TXTPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTPasswordFocusGained(evt);
            }
        });
        PNL1.add(TXTPassword);
        TXTPassword.setBounds(460, 110, 200, 40);

        CHKBXPassword.setBackground(new java.awt.Color(0, 0, 0));
        CHKBXPassword.setForeground(new java.awt.Color(255, 255, 255));
        CHKBXPassword.setText("Show Password");
        CHKBXPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHKBXPasswordActionPerformed(evt);
            }
        });
        PNL1.add(CHKBXPassword);
        CHKBXPassword.setBounds(680, 120, 130, 18);

        BTNOK.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        BTNOK.setText("OK");
        BTNOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNOKActionPerformed(evt);
            }
        });
        PNL1.add(BTNOK);
        BTNOK.setBounds(460, 220, 200, 40);

        BTNClearAll.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        BTNClearAll.setText("Clear All");
        BTNClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNClearAllActionPerformed(evt);
            }
        });
        PNL1.add(BTNClearAll);
        BTNClearAll.setBounds(460, 280, 200, 40);

        BTNBACK.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        BTNBACK.setText("Back");
        BTNBACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBACKActionPerformed(evt);
            }
        });
        PNL1.add(BTNBACK);
        BTNBACK.setBounds(30, 350, 100, 40);

        BTNExit.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        BTNExit.setText("Exit");
        BTNExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNExitActionPerformed(evt);
            }
        });
        PNL1.add(BTNExit);
        BTNExit.setBounds(690, 350, 100, 40);

        LBLBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BigBargainPhotos/Background Photo.jpg"))); // NOI18N
        PNL1.add(LBLBackground);
        LBLBackground.setBounds(0, 0, 860, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNL1, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNL1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTUserNameActionPerformed
        
    }//GEN-LAST:event_TXTUserNameActionPerformed

    private void BTNOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNOKActionPerformed
        try
        {
            //Calls the Method for checking MySQL Connection in the Class MySQLConnect. (Inheritance)
            conn = MySQLConnect.ConnectDB();
            
            //Holds the SQL Statement you write and checks whether MySQL is connected
            NewStatement = conn.createStatement();
            
            //Retrieve data for the user
            myResultSet = NewStatement.executeQuery("select * from adminlogin where UserName='" + TXTUserName.getText() + "' and Password='" + TXTPassword.getText() + "';");

            //If Result Set returns results without error
            if (myResultSet.next())
            {
                //Show that login was confirmed
                JOptionPane.showMessageDialog(null, "Welcome to the Big Bargains Administrator Platform!");
                
                //Send to the database accepted login details
                SQLCode = "insert into LoginAttempt (UserName, PasswordUsed, Date, Attempt) values ('" + TXTUserName.getText() + "', '" + TXTPassword.getText() + "', Now(), 'Successful Login');";
                executeSQLQuery(SQLCode);
                
                //Pass the UserName and the Default CartNumber to the next page
                PassingUserName();
                int cart[] = {0};
                AdminsPower.main(loggedin, cart);
                
                //Open the Next Page
                new AdminsPower().setVisible(true);
                this.setVisible(false);
                
            }

            else
            {
                //Show login has failed
                JOptionPane.showMessageDialog(null, "Invalid Login Credentials Provided", "Access Denied", JOptionPane.WARNING_MESSAGE);
                
                //Show that login was attempted. 
                SQLCode = "insert into LoginAttempt (UserName, PasswordUsed, Date, Attempt) values ('"+TXTUserName.getText()+"', '"+TXTPassword.getText()+"', Now(), 'Failed Login');";
                executeSQLQuery(SQLCode);
                
            }
        }

        catch (SQLException sqle)
        {
            JOptionPane.showMessageDialog(null, sqle.getMessage() + "\n\nRestart Database and Resubmit your Credentials (Sent From Admin Login)", "DATA RETRIEVAL ERROR", JOptionPane.ERROR_MESSAGE);
            new AdminBuyGoods1().setVisible(true);
            this.setVisible(false);
            
        }
    }//GEN-LAST:event_BTNOKActionPerformed

    private void BTNClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNClearAllActionPerformed
        TXTUserName.setText("");
        TXTPassword.setText("");
        CHKBXPassword.setSelected(false);
        CHKBXPassword.hide();
        
    }//GEN-LAST:event_BTNClearAllActionPerformed

    private void CHKBXPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHKBXPasswordActionPerformed
        if (CHKBXPassword.isSelected())
        {
            //Does not allow users to select password once written.
            TXTPassword.setEchoChar((char)0);
            
        }

        else
        {
            //Sets the password characters to *
            TXTPassword.setEchoChar('*');
            
        }
    }//GEN-LAST:event_CHKBXPasswordActionPerformed

    private void BTNExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNExitActionPerformed
        //Exit System
        System.exit(0);
        
    }//GEN-LAST:event_BTNExitActionPerformed

    private void BTNBACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBACKActionPerformed
        new ChooseUserType().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_BTNBACKActionPerformed

    private void TXTPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTPasswordFocusGained
        CHKBXPassword.show();
        CHKBXPassword.setOpaque(false);
        
    }//GEN-LAST:event_TXTPasswordFocusGained

    /**
     * @param args the command line arguments
    */
    public static void main(String args[]) {
        //Set the Nimbus look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //Create and display the form
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new CustomerLogin().setVisible(true);
                
            }
        });
    }

    //Swing Objects Declared Here
    //<editor-fold defaultstate="collapsed" desc=" Declared Variable of the Swing Objects (do not modify) ">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBACK;
    private javax.swing.JButton BTNClearAll;
    private javax.swing.JButton BTNExit;
    private javax.swing.JButton BTNOK;
    private javax.swing.JCheckBox CHKBXPassword;
    private javax.swing.JLabel LBLBackground;
    private javax.swing.JLabel LBLLogo;
    private javax.swing.JLabel LBLPassword2;
    private javax.swing.JLabel LBLUserName2;
    private javax.swing.JPanel PNL1;
    private javax.swing.JPasswordField TXTPassword;
    private javax.swing.JTextField TXTUserName;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}