package BeforeLogin;

import java.awt.Color;
import javax.swing.JOptionPane;

/**Author and License
 * 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * 
 * @author ray njire
 */
public class IndexPage extends javax.swing.JFrame 
{
    /**
     * Creates new form ModalScreen
    */
    public IndexPage() 
    {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(580, 450);
        PNL1.setSize(580, 450);
        setTitle("INDEX PAGE");
        setResizable(false);
        
    }

    /**Default Instantiation Function
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PNL1 = new javax.swing.JPanel();
        LBLLogo = new javax.swing.JLabel();
        LBLLogin = new javax.swing.JLabel();
        LBLOR = new javax.swing.JLabel();
        LBLNewUser = new javax.swing.JLabel();
        BTNNewUser1 = new javax.swing.JButton();
        LBLBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 352));
        setResizable(false);

        PNL1.setMaximumSize(new java.awt.Dimension(5000000, 3500002));
        PNL1.setMinimumSize(new java.awt.Dimension(5000000, 3000052));
        PNL1.setLayout(null);

        LBLLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BigBargainPhotos/Big Bargains Store Logo.jpg"))); // NOI18N
        LBLLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        PNL1.add(LBLLogo);
        LBLLogo.setBounds(30, 30, 300, 300);

        LBLLogin.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        LBLLogin.setForeground(new java.awt.Color(255, 255, 0));
        LBLLogin.setText("LOG IN");
        LBLLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBLLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LBLLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LBLLoginMouseExited(evt);
            }
        });
        PNL1.add(LBLLogin);
        LBLLogin.setBounds(410, 70, 70, 20);

        LBLOR.setBackground(new java.awt.Color(255, 51, 51));
        LBLOR.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        LBLOR.setForeground(new java.awt.Color(255, 255, 255));
        LBLOR.setText("OR");
        PNL1.add(LBLOR);
        LBLOR.setBounds(440, 160, 30, 22);

        LBLNewUser.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        LBLNewUser.setForeground(new java.awt.Color(255, 255, 0));
        LBLNewUser.setText("NEW USER");
        LBLNewUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LBLNewUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LBLNewUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LBLNewUserMouseExited(evt);
            }
        });
        PNL1.add(LBLNewUser);
        LBLNewUser.setBounds(400, 250, 100, 20);

        BTNNewUser1.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        BTNNewUser1.setText("Exit");
        BTNNewUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNNewUser1ActionPerformed(evt);
            }
        });
        PNL1.add(BTNNewUser1);
        BTNNewUser1.setBounds(410, 360, 100, 40);

        LBLBackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BigBargainPhotos/Background Photo.jpg"))); // NOI18N
        PNL1.add(LBLBackGround);
        LBLBackGround.setBounds(0, 0, 890, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNL1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNL1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNNewUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNNewUser1ActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_BTNNewUser1ActionPerformed

    private void LBLLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBLLoginMouseClicked
        new ChooseUserType().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_LBLLoginMouseClicked

    private void LBLNewUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBLNewUserMouseClicked
        JOptionPane.showMessageDialog(null, "Users will not have administrative priviledges");
        
        new NewCustomer().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_LBLNewUserMouseClicked

    private void LBLNewUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBLNewUserMouseEntered
        LBLNewUser.setForeground(Color.green);
        
    }//GEN-LAST:event_LBLNewUserMouseEntered

    private void LBLNewUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBLNewUserMouseExited
        LBLNewUser.setForeground(Color.yellow);
        
    }//GEN-LAST:event_LBLNewUserMouseExited

    private void LBLLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBLLoginMouseEntered
        LBLLogin.setForeground(Color.green);
        
    }//GEN-LAST:event_LBLLoginMouseEntered

    private void LBLLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LBLLoginMouseExited
        LBLLogin.setForeground(Color.yellow);
        
    }//GEN-LAST:event_LBLLoginMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndexPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndexPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndexPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndexPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndexPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNNewUser1;
    private javax.swing.JLabel LBLBackGround;
    private javax.swing.JLabel LBLLogin;
    private javax.swing.JLabel LBLLogo;
    private javax.swing.JLabel LBLNewUser;
    private javax.swing.JLabel LBLOR;
    private javax.swing.JPanel PNL1;
    // End of variables declaration//GEN-END:variables
}
