package BeforeLogin;

/**Author and License
 * 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *
 * @author ray njire
 */
public class SplashScreenInterface extends javax.swing.JFrame 
{
    /**
     * Creates new form SplashScreenInterface
     * All Codes in here are run as the Form is being created
     */
    public SplashScreenInterface() 
    {
        //Personalized Default Frame Appearance
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setCursor(WAIT_CURSOR);
        this.setUndecorated(true);
        this.setSize(750, 360);
        PNL1.setSize(750, 360);
        LBLGif.setSize(750,360);
        
        //Set Default Component Properties
        LBLWelcome.setVisible(false);
        LBLClose.setVisible(false);
        
    }
    
    /**Default Instantiation Function
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PNL1 = new javax.swing.JPanel();
        LBLTitle = new javax.swing.JLabel();
        LBLPercent = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        LBLWelcome = new javax.swing.JLabel();
        LBLGif = new javax.swing.JLabel();
        LBLClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIG BARGAINS STORE SYSTEM LOADING...");
        setResizable(false);

        PNL1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBLTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        LBLTitle.setForeground(new java.awt.Color(255, 255, 255));
        LBLTitle.setText("THE BIG BARGAINS STORE SYSTEM");
        PNL1.add(LBLTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        LBLPercent.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        LBLPercent.setForeground(new java.awt.Color(255, 255, 255));
        LBLPercent.setText("0%");
        PNL1.add(LBLPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 70, 40));
        PNL1.add(ProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 510, 40));

        LBLWelcome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        LBLWelcome.setForeground(new java.awt.Color(255, 255, 255));
        LBLWelcome.setText("WELCOME!");
        LBLWelcome.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                LBLWelcomeComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                LBLWelcomeComponentShown(evt);
            }
        });
        PNL1.add(LBLWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 160, 40));

        LBLGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BigBargainPhotos/Loading Gif.gif"))); // NOI18N
        LBLGif.setPreferredSize(null);
        PNL1.add(LBLGif, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 360));

        LBLClose.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        LBLClose.setText("CLOSE");
        LBLClose.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                LBLCloseComponentShown(evt);
            }
        });
        PNL1.add(LBLClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PNL1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PNL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(765, 396));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LBLWelcomeComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_LBLWelcomeComponentHidden
        
    }//GEN-LAST:event_LBLWelcomeComponentHidden

    private void LBLWelcomeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_LBLWelcomeComponentShown
        
    }//GEN-LAST:event_LBLWelcomeComponentShown

    private void LBLCloseComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_LBLCloseComponentShown
        this.dispose();
        
    }//GEN-LAST:event_LBLCloseComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        //Empty but I can't get rid of it :p
        
    }
    
    //Swing Objects Declared Here
    //<editor-fold defaultstate="collapsed" desc=" Declared Variable of the Swing Objects (do not modify) ">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LBLClose;
    private javax.swing.JLabel LBLGif;
    public static javax.swing.JLabel LBLPercent;
    private javax.swing.JLabel LBLTitle;
    public static javax.swing.JLabel LBLWelcome;
    private javax.swing.JPanel PNL1;
    public static javax.swing.JProgressBar ProgressBar;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
}
